sudo: required

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - docker build -t singularitynet_agent agent
  - pip install coveralls

script:
  - docker run -e SN_NETWORK_ACCOUNT_PASSWORD=abcd --volume ${PWD}/test-results:/data singularitynet_agent /bin/sh -c "./agent.sh test"

after_success:
  - coveralls
