---

services:

- service: deadbeef-aaaa-bbbb-cccc-000000000101
  module: examples.simple_adapter.SimpleAdapter

- service: deadbeef-aaaa-bbbb-cccc-111111111101
  module: adapters.tensorflow.mnist.TensorflowMNIST

- service: deadbeef-aaaa-bbbb-cccc-111111111102
  module: adapters.tensorflow.imagenet.TensorflowImageNet

- service: deadbeef-aaaa-bbbb-cccc-000000000202
  module: adapters.opencog.relex.RelexAdapter

- service: deadbeef-aaaa-bbbb-cccc-100000000002
  module: adapters.aigents.AigentsTextsClustererAdapter

- service: deadbeef-aaaa-bbbb-cccc-100000000003
  module: adapters.aigents.AigentsTextExtractorAdapter

- service: deadbeef-aaaa-bbbb-cccc-100000000004
  module: adapters.aigents.AigentsSocialGrapherAdapter

- service: deadbeef-aaaa-bbbb-cccc-100000000005
  module: adapters.aigents.AigentsRSSFeederAdapter
